### ISSUE TITLE
add F# and Ocaml!

### ISSUE THREAD

**Issue by jkone27** [github/innovationgraph#21]
plaase add F# and Ocaml in the diagram/stats

* https://dotnet.microsoft.com/en-us/languages/fsharp
* https://ocaml.org/

**Comment by mlinksva** [comment]
They're in the data https://raw.githubusercontent.com/github/innovationgraph/main/data/languages.csv just don't rank highly enough to show up in the chart on https://innovationgraph-internal.github.com/global-metrics/programming-languages at this point.
