### ISSUE TITLE
Can't export licenses to any compressed format

### ISSUE THREAD

**Issue by akirataguchi115** [github/innovationgraph#25]
While trying to export to PNG, JPEG, PDF or SVG in licenses the website loads quite a while then redirects to the following url:
![image](https://github.com/github/innovationgraph/assets/31825085/44c00039-e795-4fe4-8ac2-08d0d4c64c1e)

Can someone else reproduce this or is this only on my machine?

**Comment by mlinksva** [comment]
Thanks, I get the same error. Apparently, this is a known issue that will be fixed soon https://github.com/highcharts/node-export-server/issues/490

**Comment by akirataguchi115** [comment]
Thanks for replicating the problem. I should have searched more vigorously on highcharts' GitHub since the error they have is literally similar to mine. Sorry making you work for something I should have researched myself first, and thank you ❤️ I'll close the issue since the PR is indeed part of the next release.
