### ISSUE TITLE
About the economies data sheet

### ISSUE THREAD

**Issue by frank-zsy** [github/innovationgraph#30]
I am wondering why Germany and France are individually reported as economies but not part of the EU?

**Comment by khxu** [comment]
Oh hmm, we report data on EU member states such as Germany and France individually in the dataset files, but we also roll up the sums into `EU` for ease of analysis. For example, in https://github.com/github/innovationgraph/blob/main/data/git_pushes.csv, the `EU` rows for each quarter should be the sum of the 27 member states' git pushes for each quarter.

**Comment by frank-zsy** [comment]
@khxu Thanks for the clarification, I am using the developers count for each economies data right now, so does this mean that the developers count of EU also includes Germany and France?

**Comment by khxu** [comment]
Yep! The `EU` rows in  developers.csv would include the numbers from France and Germany.

**Comment by frank-zsy** [comment]
Thanks, this helps a lot.
