### ISSUE TITLE
ASP.NET is not a language

### ISSUE THREAD

**Issue by brphelps** [github/innovationgraph#9]
👋 

While I am SUPER interested in tracking the popularity of specific framework use, i will say that ASP.NET seems out of place in this graph. For example, we don't list Rails, so I would expect us to also not list ASP.NET.

Thanks!

**Comment by mlinksva** [comment]
Right or wrong, it is tracked as a programming language in:

https://github.com/github-linguist/linguist/blob/7ca3799b8b5f1acde1dd7a8dfb7ae849d3dfb4cd/lib/linguist/languages.yml#L175-L192

https://github.com/search?q=language%3AASP.NET&type=repositories

I imagine (haven't thought about it, people long involved in linguist probably have) that it'd be possible to break templating languages out of programming language, or reclassifies some templating languages as markup languages (which IG doesn't report on for now) but also hard, eg when would PHP be one vs the other? My default position is to assume there's just going to be some languages that are hard to categorize, especially as you go down the popularity list.

Closing for now as I don't think this is something we should address directly in this project, but feel free to add further thoughts, including why/how we should.

**Comment by brphelps** [comment]
I think it's more that we're calling something ASP.NET that actually is referring to a very very very specific subset of a classic implementation of a framework that is much more widely used than the file types in question.  

It's quite possible the name is not quite right -- that it should say "ASP.NET ASPX files" _or_ it should be surveying projects that use ASP.NET (of which there are orders of magnitude more than the # of projects using aspx files).

**Comment by mlinksva** [comment]
I think the right place to address the name would be in Linguist (which will then be reflected in the data this project uses). I don't know the ASP.NET ecosystem at all (beyond hearing that there are lots of versions) to competently suggest an accurate name. People following the Linguist repo surely have a keen interest in accurate naming -- the names show up most prominently in the GitHub repo sidebar, eg https://github.com/udacity/FCND-Gimbal-Demo
